### ISSUE TITLE
Count down voice can't be heard.

### ISSUE THREAD

**Issue by mfahel** [egingric/2013-Racing-Game#206]
Countdown
Music
Toggle Cinematic Mode
Camera fly to car

**Comment by mfahel** [comment]
Only countdown doesn't work. Also doesn't work on other people's levels, so closing this for now!

**Comment by egingric** [comment]
Does the countdown work on ANYONE else's level? If it does, then it is probably still your issue to fix.

**Comment by mfahel** [comment]
Doesn't work for anyone else I've seen or asked. Except for Rachel: for some reason the announcement is the only thing that works in her level. Kismet was copied from a level that worked, and it worked for a while until it decided to stop working. Looking at it right now, every announcement has a delay, but it still fires off at once. There are no other attachments to announcements. UDK has the tendency to not work when it's supposed to. UDK's problem, not mine. Closing!

**Comment by egingric** [comment]
Doesn't work on mine either! Another thing to ad to list of weirdness.
