### ISSUE TITLE
"Divine Intervention: part 2"  

### ISSUE THREAD

**Issue by AJSHanson** [egingric/2013-Racing-Game#258]
Ok so now the player easily touches the trigger volumes when they fall off of the path, but now we have another problem.  When the player teleports back onto the trail they are done so quickly and confusingly without much notice as to why they are where they are.  Strategically place the trigger volumes so that falling into the water becomes the sign that: "I've fallen too far off to get back on again."  Add an effect and maybe even a sound that will communicate to the player that "I've teleported because I fell off the edge."  Reinforce this by placing the respawn nodes in location that view the where they had fallen.  Example:  If I fall off the side of the ship, I want to teleport back onto the ship a couple meters before where I had dropped.  Then I can look around and say "OH! this is where I fell so now I can try again!"

**Comment by egingric** [comment]
A quick fade might help with he transition.
