### ISSUE TITLE
Lighting and Paths not built (RED warning)

### ISSUE THREAD

**Issue by egingric** [egingric/2013-Racing-Game#350]
I think your lighting may actually not be built because paths also are not built and it's RED.

**Comment by Tharmon** [comment]
Somewhat fixed. Paths are built and that message no longer shows. However, the red lighting message still does. I've built on both maps and levels. The only map I can't build on is the vehicle select map. Could that possibly be the source of the problem? Does that map have it's lighting built?

**Comment by Tharmon** [comment]
Lighting and path message no longer in my map. I dont know how it got fixed but it works now.
