### ISSUE TITLE
Invisible collision

### ISSUE THREAD

**Issue by egingric** [egingric/2013-Racing-Game#367]
Right Here:
![InvisibleCollision](https://f.cloud.github.com/assets/3945065/363888/e5e75290-a20f-11e2-8bdd-15fe84f9b11d.jpg)

**Comment by ggomezXringling** [comment]
I got rid of the collision. hopefully it doesn't bother anyone anymore

**Comment by egingric** [comment]
Why are you marking these fixed but I don't see a check from you?

**Comment by ggomezXringling** [comment]
I had marked those fixed before i checked in my level. Im sorry i should of marked those fixed when after i check them into perforce.

**Comment by ggomezXringling** [comment]
i submitted it into perforce with everything fixed
