### ISSUE TITLE
Ending does not work

### ISSUE THREAD

**Issue by mfahel** [egingric/2013-Racing-Game#385]
At race end, the camera goes to some awkward indescribable location, and there are no fireworks there. Vehicle also explodes onscreen.

![ScreenShot00002](https://f.cloud.github.com/assets/3964544/367550/627acc5a-a2ac-11e2-852e-50ec935e148e.jpg)

**Comment by dphua** [comment]
How to fix it, I'm going crazy 

Regards, 
Dionne Phua

**Comment by mfahel** [comment]
Check my level ending. You'll need a matinee with a camera shot, and you
have to put the same camera somewhere in the new kismet towards the
beginning.
