### ISSUE TITLE
end of race cam

### ISSUE THREAD

**Issue by JSumrow** [egingric/2013-Racing-Game#392]
cam follows car at end of race, then teleports to weird location. Might want something better looking for when you finish

**Comment by dphua** [comment]
That never happened before, how do you fix that?? The camera teleport to somewhere below the level, Michael already spotted that problem 

Regards, 
Dionne Phua

**Comment by JSumrow** [comment]
You'd want to make a camera, might need to give it a matinee, and then tell
the camera to be the target after the race.
