### ISSUE TITLE
Ambient Occlusion on vehicle select and level

### ISSUE THREAD

**Issue by mfahel** [egingric/2013-Racing-Game#393]
Go to the world properties menu and under the world post process settings, turn ambient occlusion off. Both check boxes, both levels!

![ScreenShot00004](https://f.cloud.github.com/assets/3964544/367795/b9ba83ce-a2b2-11e2-91bb-9050a267d49b.jpg)
![ScreenShot00003](https://f.cloud.github.com/assets/3964544/367796/b9c666a8-a2b2-11e2-9014-b673c0c4b27e.jpg)

**Comment by slundber** [comment]
fixed
