### ISSUE TITLE
Level crashes when replayed

### ISSUE THREAD

**Issue by egingric** [egingric/2013-Racing-Game#406]
Not sure if there is anything you can do but wanted to let you know that your level now crashes consistently when reloading to play it again after playing it once. Anything recently changed that might cause this? Maybe do a map check and see if there are any warnings that are easy to fix or obvious problems. Here is a snippet of the log when it crashed:

[0855.63] PerfWarning: bClothUseCompartment not set, no HW acceleration. SkeletalMeshComponent: SkeletalMeshComponent_18, SkeletalMesh: SK_Tapestry_1
[0855.63] PerfWarning: bClothUseCompartment not set, no HW acceleration. SkeletalMeshComponent: SkeletalMeshCompo

**Comment by Tharmon** [comment]
Ughhh. Alright.
Well from the perfwarning messages, its something goin wrong with Ashleys
tapestries. Thats the only cloth simulation in my level.
 Ill try deleting them n see if that fixes it.

**Comment by Tharmon** [comment]
Alex just played my map 3 times in a row, and there were no errors or
crashes. And the flags are still there and working.

I dunno what the dealio is...

On Thu, Apr 11, 2013 at 8:54 PM, Ty Christian Harmon <tharmon@c.ringling.edu

> wrote:
> 
> Ughhh. Alright.
> Well from the perfwarning messages, its something goin wrong with Ashleys
> tapestries. Thats the only cloth simulation in my level.
>  Ill try deleting them n see if that fixes it.
> 
> On Thu, Apr 11, 2013 at 8:27 PM, Eric D. Gingrich <

**Comment by egingric** [comment]
lets try rebuilding Lighting and checking it in again please ASAP.

It crashes the third time you open the map. Just run on PC, choose your map, pick vehicle, once map loads, exit back to vehicle select, go right back in to your map, repeat one more time and it should break. It is possible that this only happens on the cooked version of the game.
