### ISSUE TITLE
Start Screen - overall lighting too even

### ISSUE THREAD

**Issue by egingric** [egingric/2013-Racing-Game#407]
Could improve the overall impression if it was darker overall and only important areas like the cars and the logo were lit up. This could help the logo stand out more, especially if a light was on it and most of the scene was a bit darker, Toggle lights timed to sparks could add a dramatic touch.

**Comment by Tharmon** [comment]
Fixed lighting. Darkened background, added a few more meshes and fixed the missing barrel texture.
