### ISSUE TITLE
Can get underwater

### ISSUE THREAD

**Issue by egingric** [egingric/2013-Racing-Game#411]
If I boost out of the underground AND hit slomo I can get here. Not totally sure if this is a common thing with slomo or just this area. Maybe check your re-trigger delay and experiment with trying to replicate. Not worth checking in unless you discover something:
![UnderWaterFun](https://f.cloud.github.com/assets/3945065/371528/a7e154fc-a339-11e2-87f8-5952ef4bf7fd.jpg)

**Comment by ghost** [comment]
Scaled up the trigger volume and changed the re-trigger delay.
