### ISSUE TITLE
Title / black bars on attract

### ISSUE THREAD

**Issue by egingric** [egingric/2013-Racing-Game#472]
Please fix ASAP.

**Comment by abarlow** [comment]
The one that we handed in today? I fixed that...

**Comment by abarlow** [comment]
Hey Eric,

I resubmitted the fixed version in front of you in class today...is it not
showing up?  It was showing up earlier.  I added and submitted and
everything.

On Thu, Apr 25, 2013 at 10:22 PM, Eric D. Gingrich <notifications@github.com

**Comment by egingric** [comment]
No... you didn't check it in.

**Comment by abarlow** [comment]
Weirddd! Okay, just completely removed the file from perforce and re-added
it.  Hopefully it works this time!

On Thu, Apr 25, 2013 at 11:16 PM, Eric D. Gingrich <notifications@github.com
