### ISSUE TITLE
Narrow the road down

### ISSUE THREAD

**Issue by dphua** [egingric/2013-Racing-Game#63]
I think you should make the open area a little more tight for the player to drive in because when I playtest it, i felt that the neon signs alone is not enough to guide me

**Comment by ghost** [comment]
This is still intended to be a multiplayer level. I can't make the roads much narrower than they are.

**Comment by egingric** [comment]
Yes, but can you solve the issue of a player not being able to find their way? Can you give more details Dionne? @dphua

**Comment by dphua** [comment]
Probably use a different texture to indicate the race road and the "side" road that players aren't suppose to be on. The "side" road could be grey pavement? Or dark red.

Regards, 
Dionne Phua

**Comment by ghost** [comment]
There shouldn't be any road that you're not supposed to be on. If there's somewhere you're getting lost or stuck, let me know where. And much of the pavement is currently bordered by sidewalk chunks.

**Comment by ghost** [comment]
Added tons more sidewalks and painted lines to border the edge of the road and direct the player.
