### ISSUE TITLE
Jump Before the Underground

### ISSUE THREAD

**Issue by MACrocker** [egingric/2013-Racing-Game#71]
Perhaps turn the jump or lower the strength of the boost, I had to slow down my car each time I took a boost, otherwise I would crash into buildings (as in before even landing).

**Comment by ghost** [comment]
I have reduced the intensity of the boost significantly. If you are still flying off the edge, I suggest upping the density on your vehicle. If I reduce the boosts any more, they will have no effect on heavier vehicles.
