### ISSUE TITLE
Force Actor...?

### ISSUE THREAD

**Issue by ainganam** [egingric/2013-Racing-Game#95]
In the room with the purple particles and the elevated floors/falling cubes, It definitely feels as though I'm being pulled toward the edge by some greater force... Not sure if this is intentional, perhaps it was the car I was driving, but yeah. It slowed the game quite a bit.

**Comment by MACrocker** [comment]
I believe that this issue has been fixed, I changed the NxForceActors to RBForceActors and disabled the vehicle collision channel.
